### ISSUE TITLE
Step running

### ISSUE THREAD

**Issue by Manssizz** [dickymuliafiqri/Spider#41]
bisa tambah md untuk runningnya om? soalnya belum pernah running pakai bot action.
untuk action testing result udah muncul 0 di tele, tapi di crawl internet belum paham runningnya

**Comment by dickymuliafiqri** [comment]
Untuk crawling nya pake bantuan pihak ketiga untuk saat ini, tapi sebenernya gampang.

Kalo dijalankan di terminal cukup kasi index yang ingin discan, indexnya bisa dilihat di `sub-list.json`.

Contoh
npx tsc && node app/index.js 3
3 -> Index yang akan discan.

Kalo index yang dimasukkan melebihi index yang ada di .json itu tadi, maka bot nya akan generate isi folder result.


Btw saya ada rencana untuk refactoring kode nya, jadi kemungkinan akan ada yang banyak berubah. Mending tunggu saya selesai dulu baru coba jalanin sendiri.


Untuk file .md tutorial running nya nanti akan saya buat kalo sudah selesai.

**Comment by Manssizz** [comment]
wokay. udah berapa kali rebase ini fork saya 😆
